#!/usr/bin/env python3
"""Utility to compare compiled requirements against the committed lockfile."""
from __future__ import annotations

import argparse
import re
from pathlib import Path

COMMAND_LINE = (
    "#    uv pip compile pyproject.toml --extra app --extra dev "
    "--extra notebooks -o requirements.lock"
)
AUTOGEN_PATTERN = re.compile(r"^#.*autogenerated.*by.*", re.IGNORECASE)
UV_PATTERN = re.compile(r"^#\s*uv pip compile.*", re.IGNORECASE)
DATE_PATTERN = re.compile(r"\d{4}-\d{2}-\d{2}")
TIME_PATTERN = re.compile(r"\d{2}:\d{2}")


def normalize(content: str) -> str:
    """Strip timestamps and non-deterministic comments for stable comparisons."""
    lines: list[str] = []
    for raw in content.splitlines():
        stripped = raw.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            if AUTOGEN_PATTERN.match(stripped):
                continue
            if UV_PATTERN.match(stripped):
                lines.append(COMMAND_LINE)
                continue
            if DATE_PATTERN.search(stripped) or TIME_PATTERN.search(stripped):
                continue
            lines.append(stripped)
        else:
            lines.append(stripped)
    return "\n".join(lines) + ("\n" if lines else "")


def determine_status(compiled_path: Path, lockfile_path: Path) -> str:
    compiled = normalize(compiled_path.read_text())
    existing = normalize(lockfile_path.read_text())
    return "CURRENT" if compiled == existing else "OUTDATED"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare compiled requirements to lockfile")
    parser.add_argument("--compiled", type=Path, default=Path("/tmp/requirements.compiled"))
    parser.add_argument("--lockfile", type=Path, default=Path("requirements.lock"))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    status = determine_status(args.compiled, args.lockfile)
    print(status)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
