"""Tests for lockfile_status.py normalization and status determination."""

import importlib.util
import sys
from pathlib import Path

import pytest

# Load the lockfile_status module from .github/scripts/
_REPO_ROOT = (
    Path(__file__).resolve().parents[3]
)  # .github/scripts/__tests__ -> .github/scripts -> .github -> repo root
_SCRIPT_PATH = _REPO_ROOT / ".github" / "scripts" / "lockfile_status.py"

_lockfile_status_spec = importlib.util.spec_from_file_location("lockfile_status", _SCRIPT_PATH)
if _lockfile_status_spec is None or _lockfile_status_spec.loader is None:
    raise RuntimeError("Unable to load lockfile_status module")

lockfile_status_module = importlib.util.module_from_spec(_lockfile_status_spec)
_lockfile_status_spec.loader.exec_module(lockfile_status_module)

# Import the functions we need
COMMAND_LINE = lockfile_status_module.COMMAND_LINE
determine_status = lockfile_status_module.determine_status
main = lockfile_status_module.main
normalize = lockfile_status_module.normalize


class TestNormalize:
    """Test normalize() function behavior."""

    def test_removes_autogenerated_comments(self) -> None:
        """Autogenerated comments should be stripped."""
        input_text = "# This file is autogenerated by some tool\npackage==1.0.0"
        expected = "package==1.0.0\n"
        assert normalize(input_text) == expected

    def test_removes_autogenerated_comments_case_insensitive(self) -> None:
        """Autogenerated detection should be case-insensitive."""
        input_text = "# This file is AUTOGENERATED BY uv pip compile\npackage==1.0.0"
        expected = "package==1.0.0\n"
        assert normalize(input_text) == expected

    def test_normalizes_uv_pip_compile_lines(self) -> None:
        """Various uv pip compile comment forms should normalize to COMMAND_LINE."""
        input_text = "#    uv pip compile requirements.in -o requirements.lock\npackage==1.0.0"
        expected = f"{COMMAND_LINE}\npackage==1.0.0\n"
        assert normalize(input_text) == expected

    def test_normalizes_uv_pip_compile_with_different_spacing(self) -> None:
        """uv pip compile lines with different spacing should all normalize."""
        input_text = "# uv pip compile requirements.in -o requirements.lock\npackage==1.0.0"
        expected = f"{COMMAND_LINE}\npackage==1.0.0\n"
        assert normalize(input_text) == expected

    def test_removes_date_comments(self) -> None:
        """Comments containing dates (YYYY-MM-DD) should be stripped."""
        input_text = "# Compiled on 2024-06-28\npackage==1.0.0"
        expected = "package==1.0.0\n"
        assert normalize(input_text) == expected

    def test_removes_time_comments(self) -> None:
        """Comments containing times (HH:MM) should be stripped."""
        input_text = "# Compiled at 14:30\npackage==1.0.0"
        expected = "package==1.0.0\n"
        assert normalize(input_text) == expected

    def test_preserves_deterministic_comments(self) -> None:
        """Non-autogenerated, non-timestamp comments should be preserved."""
        input_text = "# This is a deterministic comment\npackage==1.0.0"
        expected = "# This is a deterministic comment\npackage==1.0.0\n"
        assert normalize(input_text) == expected

    def test_drops_blank_lines(self) -> None:
        """Blank lines should be removed from the output."""
        input_text = "package==1.0.0\n\n\npackage==2.0.0"
        expected = "package==1.0.0\npackage==2.0.0\n"
        assert normalize(input_text) == expected

    def test_drops_leading_and_trailing_blank_lines(self) -> None:
        """Leading and trailing blank lines should be removed."""
        input_text = "\n\npackage==1.0.0\n\n"
        expected = "package==1.0.0\n"
        assert normalize(input_text) == expected

    def test_preserves_whitespace_within_lines(self) -> None:
        """Whitespace within non-comment lines should be preserved."""
        input_text = "package  ==  1.0.0"
        expected = "package  ==  1.0.0\n"
        assert normalize(input_text) == expected

    def test_empty_string(self) -> None:
        """Empty string should return empty string."""
        assert normalize("") == ""

    def test_only_blank_lines(self) -> None:
        """Only blank lines should return empty string."""
        assert normalize("\n\n\n") == ""

    def test_only_comments_removed(self) -> None:
        """If all lines are removed comments, should return empty string."""
        input_text = "# autogenerated by tool\n# 2024-06-28\n# 14:30"
        assert normalize(input_text) == ""

    def test_complex_mixed_content(self) -> None:
        """Complex mix of different comment types and content."""
        input_text = """# This is a kept comment
# autogenerated by tool on 2024-06-28 at 14:30
#    uv pip compile requirements.in -o requirements.lock

package==1.0.0

# Another kept comment
# Generated: 2024-06-28
requests>=2.0.0
"""
        expected = """# This is a kept comment
#    uv pip compile [normalized inputs] -o requirements.lock
package==1.0.0
# Another kept comment
requests>=2.0.0\n"""
        assert normalize(input_text) == expected

    def test_multiline_comprehensive(self) -> None:
        """Comprehensive test with all normalization scenarios."""
        input_text = """#  File auto-generated by  uv pip compile on  2024-06-28  at  14:30:00
# This is a real comment

# uv pip compile  requirements.in -o lock.txt

django==5.0.0

# Another real comment
# Date: 2024-01-01
requests==2.31.0

# Time: 12:00
flask==3.0.0
"""
        expected = """# This is a real comment
#    uv pip compile [normalized inputs] -o requirements.lock
django==5.0.0
# Another real comment
requests==2.31.0
flask==3.0.0\n"""
        assert normalize(input_text) == expected


class TestDetermineStatus:
    """Test determine_status() function behavior."""

    def test_current_status_when_normalized_equal(self, tmp_path: Path) -> None:
        """Should return CURRENT when normalized compiled and lockfile are equal."""
        compiled_path = tmp_path / "compiled.txt"
        lockfile_path = tmp_path / "lockfile.txt"

        compiled_content = """# autogenerated on 2024-06-28
# uv pip compile requirements.in -o lock.txt
package==1.0.0"""

        lockfile_content = """# uv pip compile requirements.in -o lock.txt
# Generated: 2024-06-28
package==1.0.0"""

        compiled_path.write_text(compiled_content)
        lockfile_path.write_text(lockfile_content)

        status = determine_status(compiled_path, lockfile_path)
        assert status == "CURRENT"

    def test_outdated_status_when_dependency_differs(self, tmp_path: Path) -> None:
        """Should return OUTDATED when there are real dependency differences."""
        compiled_path = tmp_path / "compiled.txt"
        lockfile_path = tmp_path / "lockfile.txt"

        compiled_content = "package==2.0.0"
        lockfile_content = "package==1.0.0"

        compiled_path.write_text(compiled_content)
        lockfile_path.write_text(lockfile_content)

        status = determine_status(compiled_path, lockfile_path)
        assert status == "OUTDATED"

    def test_outdated_status_when_extra_dependency(self, tmp_path: Path) -> None:
        """Should return OUTDATED when compiled has extra dependencies."""
        compiled_path = tmp_path / "compiled.txt"
        lockfile_path = tmp_path / "lockfile.txt"

        compiled_content = "package==1.0.0\nextra==1.0.0"
        lockfile_content = "package==1.0.0"

        compiled_path.write_text(compiled_content)
        lockfile_path.write_text(lockfile_content)

        status = determine_status(compiled_path, lockfile_path)
        assert status == "OUTDATED"

    def test_outdated_status_when_missing_dependency(self, tmp_path: Path) -> None:
        """Should return OUTDATED when compiled is missing dependencies."""
        compiled_path = tmp_path / "compiled.txt"
        lockfile_path = tmp_path / "lockfile.txt"

        compiled_content = "package==1.0.0"
        lockfile_content = "package==1.0.0\nextra==1.0.0"

        compiled_path.write_text(compiled_content)
        lockfile_path.write_text(lockfile_content)

        status = determine_status(compiled_path, lockfile_path)
        assert status == "OUTDATED"

    def test_current_status_when_both_empty(self, tmp_path: Path) -> None:
        """Should return CURRENT when both files are empty."""
        compiled_path = tmp_path / "compiled.txt"
        lockfile_path = tmp_path / "lockfile.txt"

        compiled_path.write_text("")
        lockfile_path.write_text("")

        status = determine_status(compiled_path, lockfile_path)
        assert status == "CURRENT"

    def test_current_status_when_only_comments_differ(self, tmp_path: Path) -> None:
        """Should return CURRENT when only comment differences exist after normalization."""
        compiled_path = tmp_path / "compiled.txt"
        lockfile_path = tmp_path / "lockfile.txt"

        compiled_content = """# uv pip compile requirements.in -o lock.txt
# 2024-06-28
package==1.0.0"""

        lockfile_content = """# autogenerated by tool
# uv pip compile requirements.in -o different.txt
# 2024-06-27
package==1.0.0"""

        compiled_path.write_text(compiled_content)
        lockfile_path.write_text(lockfile_content)

        status = determine_status(compiled_path, lockfile_path)
        assert status == "CURRENT"


class TestMain:
    """Test main() function with command-line arguments."""

    def test_main_prints_current(self, tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
        """main() should print CURRENT for equivalent files."""
        compiled_path = tmp_path / "compiled.txt"
        lockfile_path = tmp_path / "lockfile.txt"

        content = "package==1.0.0"
        compiled_path.write_text(content)
        lockfile_path.write_text(content)

        # Temporarily modify sys.argv to pass custom paths

        original_argv = sys.argv.copy()
        try:
            sys.argv = [
                "lockfile_status.py",
                "--compiled",
                str(compiled_path),
                "--lockfile",
                str(lockfile_path),
            ]
            result = main()
            assert result == 0
            captured = capsys.readouterr()
            assert captured.out.strip() == "CURRENT"
        finally:
            sys.argv = original_argv

    def test_main_prints_outdated(self, tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
        """main() should print OUTDATED for different files."""
        compiled_path = tmp_path / "compiled.txt"
        lockfile_path = tmp_path / "lockfile.txt"

        compiled_path.write_text("package==2.0.0")
        lockfile_path.write_text("package==1.0.0")

        original_argv = sys.argv.copy()
        try:
            sys.argv = [
                "lockfile_status.py",
                "--compiled",
                str(compiled_path),
                "--lockfile",
                str(lockfile_path),
            ]
            result = main()
            assert result == 0
            captured = capsys.readouterr()
            assert captured.out.strip() == "OUTDATED"
        finally:
            sys.argv = original_argv

    def test_main_uses_explicit_paths(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """main() should work with explicit --compiled and --lockfile paths."""
        compiled_path = tmp_path / "compiled.lock"
        lockfile_path = tmp_path / "lockfile.lock"

        content = "package==1.0.0"
        compiled_path.write_text(content)
        lockfile_path.write_text(content)

        original_argv = sys.argv.copy()
        try:
            sys.argv = [
                "lockfile_status.py",
                "--compiled",
                str(compiled_path),
                "--lockfile",
                str(lockfile_path),
            ]
            result = main()
            assert result == 0
            captured = capsys.readouterr()
            assert captured.out.strip() == "CURRENT"
        finally:
            sys.argv = original_argv
