# Basic Python CI Template
#
# Copy this file to your repo's .github/workflows/ directory and customize.
# This provides: Python setup, linting (ruff), formatting (black), and pytest.
#
# CUSTOMIZE: Replace YOUR_PACKAGE_NAME with your actual package name.

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linters
        run: pip install black ruff

      - name: Check formatting
        run: black --check .

      - name: Run linter
        run: ruff check .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          pip install -e '.[dev]'
          # Or if using requirements.lock:
          # pip install uv && uv pip sync requirements.lock

      # CUSTOMIZE: Update module name
      - name: Verify imports
        run: |
          python -c "import YOUR_PACKAGE_NAME; print('Import OK')"

      # CUSTOMIZE: Update test path if needed
      - name: Run tests
        run: pytest tests/ -v

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mypy
        run: pip install mypy

      # CUSTOMIZE: Update source directory
      - name: Run mypy
        run: mypy src/ --ignore-missing-imports
