# Cosmetic Repair Template
#
# Copy this file to your repo's .github/workflows/ directory.
# This workflow auto-fixes cosmetic issues (formatting, docstrings) and opens a PR.
#
# Prerequisites:
# - black, ruff, isort installed as dev dependencies
# - Optionally: scripts/ci_cosmetic_repair.py for advanced repairs
#
# Note: This is a simplified version. For the full cosmetic repair system
# with pytest failure classification, copy from stranske/Workflows.

name: Cosmetic Repair

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Preview changes without creating PR'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  repair:
    name: Apply cosmetic fixes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install formatters
        run: pip install black ruff isort docformatter

      # CUSTOMIZE: Update paths to match your project
      - name: Apply Black formatting
        run: black src/ tests/ scripts/ || true

      - name: Apply isort import sorting
        run: isort src/ tests/ scripts/ || true

      - name: Apply Ruff fixes
        run: ruff check --fix src/ tests/ scripts/ || true

      - name: Apply docformatter
        run: |
          docformatter --in-place --recursive src/ || true

      - name: Check for changes
        id: diff
        run: |
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No cosmetic fixes needed"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "Cosmetic fixes applied:"
            git diff --stat
          fi

      - name: Create pull request
        if: steps.diff.outputs.changed == 'true' && inputs.dry-run != true
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'style: apply cosmetic fixes'
          title: 'style: automated cosmetic repairs'
          body: |
            ## Automated Cosmetic Repairs

            This PR applies automated formatting and style fixes:
            - Black formatting
            - Import sorting (isort)
            - Ruff auto-fixes
            - Docstring formatting

            **Files changed:**
            ```
            ${{ steps.diff.outputs.files || 'See diff for details' }}
            ```

            ---
            _Generated by cosmetic-repair workflow_
          branch: style/cosmetic-repair-${{ github.run_number }}
          delete-branch: true
          labels: style, automated

      - name: Show dry-run diff
        if: inputs.dry-run == true && steps.diff.outputs.changed == 'true'
        run: |
          echo "## Dry Run - Changes that would be made:"
          git diff
