# Dependency Refresh Template
#
# Copy this file to your repo's .github/workflows/ directory.
# This workflow runs on a schedule to keep your requirements.lock up to date.
#
# Prerequisites:
# - pyproject.toml with extras defined (dev, app, etc.)
# - requirements.lock file in repo root
#
# CUSTOMIZE: Update the extras list to match your pyproject.toml

name: Dependency Refresh

on:
  schedule:
    # Run on 1st and 15th of each month at 4:00 UTC
    - cron: '0 4 1,15 * *'
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Preview only (do not open a pull request)'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  refresh:
    name: Refresh dependency pins
    runs-on: ubuntu-latest
    env:
      DRY_RUN: ${{ inputs.dry-run || 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      # CUSTOMIZE: Update --extra flags to match your pyproject.toml
      - name: Refresh requirements.lock
        run: |
          uv pip compile \
            --upgrade \
            pyproject.toml \
            --extra dev \
            -o requirements.lock

      - name: Check for changes
        id: diff
        run: |
          if git diff --quiet requirements.lock; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No dependency updates"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "Updates found:"
            git diff --stat requirements.lock
          fi

      - name: Create pull request
        if: steps.diff.outputs.changed == 'true' && env.DRY_RUN != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): refresh requirements.lock'
          title: 'chore(deps): scheduled dependency refresh'
          body: |
            ## Automated Dependency Refresh

            This PR updates `requirements.lock` with the latest compatible versions.

            **Changes:**
            ```
            ${{ steps.diff.outputs.changes || 'See diff for details' }}
            ```

            ---
            _Generated by dependency-refresh workflow_
          branch: deps/refresh-${{ github.run_number }}
          delete-branch: true
          labels: dependencies, automated
