#!/usr/bin/env python3
"""Generate the consumer Renovate ownership preset from the sync manifest.

Maint 68 overwrites manifest-managed paths in every registered consumer repo on
each sync. When a consumer's own Renovate opens a PR that edits one of those
paths, the change is discarded on the next sync (for example Inv-Man-Intake#838
and Manager-Database#1347, both closed unmerged). This script compiles the
overwrite-managed target paths out of ``.github/sync-manifest.yml`` and emits a
Renovate preset that disables dependency extraction for exactly those paths in
exactly the repos where Maint 68 owns them.

Ownership follows the same rules maint-68-sync-consumer-repos.yml applies:

* ``skip_repos`` means the file is never delivered there, so the consumer owns
  any local copy and Renovate stays enabled.
* ``sync_mode: create_only`` means the file is seeded once and then owned by the
  consumer, so Renovate stays enabled -- unless the repo is listed in
  ``overwrite_repos``, which opts it back into byte-alignment with the template.
* Every other entry is overwrite-managed and must be invisible to consumer
  Renovate.

``stranske/Workflows`` is the sync source rather than a consumer, so it never
appears in ``matchRepositories`` and its canonical source files stay fully
Renovate-managed.

Usage:
  python scripts/generate_consumer_renovate_ownership.py            # write preset
  python scripts/generate_consumer_renovate_ownership.py --check    # fail on drift
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.list_registered_consumer_repos import extract_repos  # noqa: E402
from scripts.sync_manifest_compiler import (  # noqa: E402
    ManifestCompileError,
    ManifestEntry,
    compile_manifest,
)

DEFAULT_MANIFEST = Path(".github/sync-manifest.yml")
DEFAULT_SYNC_WORKFLOW = Path(".github/workflows/maint-68-sync-consumer-repos.yml")
DEFAULT_OUTPUT = Path("renovate-presets/consumer-managed-paths.json")
SOURCE_REPO = "stranske/Workflows"

PRESET_DESCRIPTION = (
    "GENERATED by scripts/generate_consumer_renovate_ownership.py -- do not edit by hand. "
    "Disables Renovate dependency extraction for the paths that "
    "maint-68-sync-consumer-repos.yml overwrites from .github/sync-manifest.yml, and only in "
    "the consumer repos where that overwrite actually applies. Without this boundary a "
    "consumer's Renovate opens PRs against centrally-copied files (Inv-Man-Intake#838, "
    "Manager-Database#1347) that the next sync silently reverts. Renovate stays enabled for "
    "create-only/skipped paths the consumer owns, and for every canonical source file in "
    f"{SOURCE_REPO}, which is the sync source rather than a consumer. Regenerate with "
    "`python scripts/generate_consumer_renovate_ownership.py`; `--check` fails on drift and "
    "runs in scripts/dev_check.sh."
)


def is_overwrite_managed(entry: ManifestEntry, repo: str) -> bool:
    """Return whether Maint 68 overwrites ``entry``'s target in ``repo``."""
    if repo in {rule.repo for rule in entry.skip_repos}:
        return False
    return not (entry.sync_mode == "create_only" and repo not in entry.overwrite_repos)


def match_pattern(entry: ManifestEntry) -> str:
    """Return the Renovate ``matchFileNames`` glob for ``entry``'s target."""
    return f"{entry.target}/**" if entry.is_directory else entry.target


def managed_paths_by_repo(
    entries: list[ManifestEntry], consumers: list[str]
) -> dict[str, list[str]]:
    """Map each consumer repo to the manifest-managed paths Renovate must skip."""
    by_repo: dict[str, list[str]] = {}
    for repo in consumers:
        if repo == SOURCE_REPO:
            continue
        managed = sorted(
            {match_pattern(entry) for entry in entries if is_overwrite_managed(entry, repo)}
        )
        if managed:
            by_repo[repo] = managed
    return by_repo


def build_package_rules(entries: list[ManifestEntry], consumers: list[str]) -> list[dict[str, Any]]:
    """Emit a shared base rule plus per-repo deltas.

    Every rule disables, so the rules are purely additive: a repo's effective
    disabled set is the union of the rules that match it. That keeps the preset
    a fraction of the size of one full path list per repo without needing an
    ``enabled: true`` override, which would be order-sensitive.
    """
    by_repo = managed_paths_by_repo(entries, consumers)
    if not by_repo:
        return []

    shared = sorted(set.intersection(*(set(paths) for paths in by_repo.values())))
    rules: list[dict[str, Any]] = []
    if shared:
        rules.append(
            {
                "description": (
                    f"Maint 68 overwrites these {len(shared)} manifest-managed paths in every "
                    "registered consumer; Renovate edits there are reverted on the next sync."
                ),
                "matchRepositories": sorted(by_repo),
                "matchFileNames": shared,
                "enabled": False,
            }
        )

    shared_set = set(shared)
    grouped: dict[tuple[str, ...], list[str]] = defaultdict(list)
    for repo, paths in by_repo.items():
        grouped[tuple(paths)].append(repo)

    for paths, repos in sorted(grouped.items(), key=lambda item: sorted(item[1])):
        extra = sorted(set(paths) - shared_set)
        if not extra:
            continue
        rules.append(
            {
                "description": (
                    f"{', '.join(sorted(repos))} additionally has {len(extra)} manifest-managed "
                    "path(s) that at least one other consumer owns via skip_repos, create_only, "
                    "or an overwrite_repos opt-in."
                ),
                "matchRepositories": sorted(repos),
                "matchFileNames": extra,
                "enabled": False,
            }
        )
    return rules


def build_preset(
    *,
    manifest: Path,
    sync_workflow: Path,
    repo_root: Path,
) -> dict[str, Any]:
    compiled = compile_manifest(manifest, repo_root=repo_root)
    consumers = extract_repos(sync_workflow)
    if not consumers:
        raise ValueError(f"No registered consumer repos found in {sync_workflow}")
    return {
        "$schema": "https://docs.renovatebot.com/renovate-schema.json",
        "description": PRESET_DESCRIPTION,
        "packageRules": build_package_rules(compiled.all_entries(), consumers),
    }


def render(preset: dict[str, Any]) -> str:
    return json.dumps(preset, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--sync-workflow", type=Path, default=DEFAULT_SYNC_WORKFLOW)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Repository root used to resolve manifest sources (default: manifest's repo)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when the committed preset differs from the generated one",
    )
    args = parser.parse_args(argv)

    repo_root = (
        args.repo_root if args.repo_root is not None else args.manifest.resolve().parent.parent
    )
    try:
        rendered = render(
            build_preset(
                manifest=args.manifest,
                sync_workflow=args.sync_workflow,
                repo_root=repo_root,
            )
        )
    except (OSError, ManifestCompileError, ValueError) as exc:
        print(f"::error::{exc}", file=sys.stderr)
        return 1

    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.is_file() else ""
        if current != rendered:
            print(
                f"{args.output} is stale. Run "
                "`python scripts/generate_consumer_renovate_ownership.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{args.output} is up to date.")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
