from __future__ import annotations

from pathlib import Path
from unittest.mock import Mock

import pytest
from scripts import sync_dev_dependencies as sdd


@pytest.mark.parametrize("inline", [True, False])
@pytest.mark.parametrize(
    "versions", [("==7.0", "==7.1"), ("==7.1", "==7.0"), (">=7.1", "==7.1"), ("==7.1", "==7.1")]
)
def test_sync_pyproject_updates_every_marker_occurrence(tmp_path, inline, versions):
    requirements = [
        f"coverage[toml]{versions[0]}; python_version < '3.11'",
        f"coverage[toml]{versions[1]}; python_version >= '3.11'",
    ]
    separator = ", " if inline else ",\n    "
    deps = separator.join(f'"{item}"' for item in requirements)
    original = "[project.optional-dependencies]\ndev = [" + deps + "]\n"
    if not inline:
        original = "[project.optional-dependencies]\ndev = [\n    " + deps + ",\n]\n"
    project = tmp_path / "pyproject.toml"
    project.write_text(original)
    changes, errors = sdd.sync_pyproject(project, {"COVERAGE_VERSION": "7.1"}, apply=True)
    assert not errors
    assert bool(changes) == (versions != ("==7.1", "==7.1"))
    expected = original.replace(versions[0] + "; python_version <", "==7.1; python_version <")
    expected = expected.replace(versions[1] + "; python_version >=", "==7.1; python_version >=")
    assert project.read_text() == expected
    assert sdd.sync_pyproject(project, {"COVERAGE_VERSION": "7.1"}, apply=True) == ([], [])


@pytest.mark.parametrize("inline", [True, False])
@pytest.mark.parametrize(
    "requirement",
    ["coverage[toml]==7.0", "coverage[toml]", "coverage[toml]>=7.0; python_version < '3.14'"],
)
def test_sync_pyproject_extras_end_to_end(tmp_path, requirement, inline):
    deps = f'dev = ["{requirement}"]\n' if inline else f'dev = [\n    "{requirement}",\n]\n'
    project = tmp_path / "pyproject.toml"
    project.write_text(
        '[project]\nname="example"\nversion="1"\n[project.optional-dependencies]\n' + deps
    )
    changes, errors = sdd.sync_pyproject(project, {"COVERAGE_VERSION": "7.1"}, apply=True)
    assert changes and not errors
    assert "coverage[toml]==7.1" in project.read_text()
    if ";" in requirement:
        assert "; python_version < '3.14'" in project.read_text()


@pytest.mark.parametrize(
    "requirement",
    ["coverage[toml]==7.0", "coverage[toml]", "coverage[toml]>=7.0; python_version < '3.14'"],
)
def test_sync_dependency_extras_before_version_preserves_marker(requirement):
    section = f'dev = ["{requirement}"]'
    assert sdd.extract_dependencies(section)[0][0] == "coverage"
    updated, changed = sdd.update_dependency_in_section(section, "coverage", "7.1")
    assert changed
    marker = "; python_version < '3.14'" if ";" in requirement else ""
    assert updated == f'dev = ["coverage[toml]==7.1{marker}"]'


@pytest.mark.parametrize(
    "group,valid",
    [
        ("nested/pyproject.toml:dev", True),
        ("/outside/pyproject.toml:dev", False),
        ("../outside/pyproject.toml:dev", False),
    ],
)
def test_regenerate_explicit_group_validates_its_actual_input(tmp_path, monkeypatch, group, valid):
    monkeypatch.chdir(tmp_path)
    Path("nested").mkdir()
    Path("nested/pyproject.toml").write_text("[dependency-groups]\ndev=[]\n")
    # A root project must neither authorize an escaped group nor be required
    # when a legitimate local group supplies its own project.
    if not valid:
        Path("pyproject.toml").write_text("[dependency-groups]\ndev=[]\n")
    lock = Path("requirements.lock")
    lock.write_text(f"# uv pip compile --group {group} -o requirements.lock\nmypy==2.4.0\n")
    run = Mock()
    monkeypatch.setattr(sdd.subprocess, "run", run)
    _, errors = sdd.regenerate_lockfile(lock, {"MYPY_VERSION": "2.4.0"})
    assert bool(errors) is not valid
    assert run.called is valid


def test_main_rejects_escaped_write_before_any_direct_pin_mutation(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    env = Path("pins.env")
    env.write_text("MYPY_VERSION=2.4.0\n")
    project = Path("pyproject.toml")
    project.write_text(
        '[project]\nname="example"\nversion="1"\n[project.optional-dependencies]\ndev=["mypy==2.3.0"]\n'
    )
    external = tmp_path.parent / "external-before-write.lock"
    original = "# uv pip compile pyproject.toml -o requirements.lock\nmypy==2.3.0\n"
    external.write_text(original)
    Path("requirements.lock").symlink_to(external)
    before = project.read_text()
    assert sdd.main(["--apply", "--resolve-locks", "--pin-file", str(env)]) == 2
    assert external.read_text() == original
    assert project.read_text() == before


def test_regenerate_lock_retains_original_extras_and_platform(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    Path("pyproject.toml").write_text("[project]\nname='example'\nversion='1'\n")
    lock = Path("requirements.lock")
    lock.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile pyproject.toml --extra=app --extra dev --universal "
        "--output-file=requirements.lock\nast-serialize==0.6.0\nmypy==2.4.0\n"
    )
    run = Mock(
        side_effect=lambda *_args, **_kwargs: lock.write_text(lock.read_text() + "# resolved\n")
    )
    monkeypatch.setattr(sdd.subprocess, "run", run)
    changes, errors = sdd.regenerate_lockfile(lock, {"MYPY_VERSION": "2.4.0"})
    assert errors == []
    assert changes == ["requirements.lock: regenerated transitive dependencies"]
    args = run.call_args.args[0]
    assert args[:4] == ["uv", "pip", "compile", "pyproject.toml"]
    assert "--extra=app" in args and args[args.index("--extra") + 1] == "dev"
    assert "--universal" in args
    assert args[-2:] == ["--upgrade-package", "mypy==2.4.0"]
    assert run.call_args.kwargs == {"check": True}


@pytest.mark.parametrize(
    "command",
    [
        "pip-compile pyproject.toml -o requirements.lock",
        "uv pip compile pyproject.toml -o ../requirements.lock",
        "uv pip compile ../pyproject.toml -o requirements.lock",
        "uv pip compile pyproject.toml -o requirements.lock ; touch owned",
        "uv pip compile pyproject.toml --unknown-flag -o requirements.lock",
        "uv pip compile pyproject.toml --no-header -o requirements.lock",
    ],
)
def test_regenerate_lock_rejects_unsupported_provenance(tmp_path, monkeypatch, command):
    monkeypatch.chdir(tmp_path)
    Path("pyproject.toml").write_text("[project]\nname='example'\nversion='1'\n")
    lock = Path("requirements.lock")
    lock.write_text(
        f"# This file was autogenerated by uv via the following command:\n#    {command}\nmypy==2.4.0\n"
    )
    run = Mock()
    monkeypatch.setattr(sdd.subprocess, "run", run)
    changes, errors = sdd.regenerate_lockfile(lock, {"MYPY_VERSION": "2.4.0"})
    assert changes == [] and errors
    run.assert_not_called()


@pytest.mark.parametrize("hashed", [False, True])
@pytest.mark.parametrize("recorded_upgrade", [False, True])
def test_regenerate_lock_replays_own_canonical_upgrade(
    tmp_path, monkeypatch, hashed, recorded_upgrade
):
    monkeypatch.chdir(tmp_path)
    Path("requirements.in").write_text("mypy>=2\n")
    lock = Path("requirements.lock")
    continuation = " \\" if hashed else ""
    upgrade = "--upgrade-package mypy==2.3.0 " if recorded_upgrade else ""
    lock.write_text(
        "# uv pip compile requirements.in "
        + upgrade
        + "--generate-hashes -o requirements.lock\nmypy==2.3.0"
        + continuation
        + "\n"
    )
    run = Mock(
        side_effect=lambda *_args, **_kwargs: lock.write_text(lock.read_text() + "# resolved\n")
    )
    monkeypatch.setattr(sdd.subprocess, "run", run)
    changes, errors = sdd.regenerate_lockfile(lock, {"MYPY_VERSION": "2.4.0"})
    assert changes and not errors
    args = run.call_args.args[0]
    assert "mypy==2.3.0" not in args
    assert args.count("mypy==2.4.0") == 1


def test_regenerate_lock_retains_consumer_baseline_txt(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    Path("pyproject.toml").write_text("[project]\nname='example'\nversion='1'\n")
    baseline = Path("tests/baseline/requirements-baseline.txt")
    baseline.parent.mkdir(parents=True)
    baseline.write_text("example==1\n")
    lock = Path("requirements.lock")
    lock.write_text(
        "# uv pip compile pyproject.toml tests/baseline/requirements-baseline.txt "
        "--extra=dev --universal --output-file=requirements.lock\nmypy==2.4.0\n"
    )
    run = Mock(
        side_effect=lambda *_args, **_kwargs: lock.write_text(lock.read_text() + "# resolved\n")
    )
    monkeypatch.setattr(sdd.subprocess, "run", run)
    changes, errors = sdd.regenerate_lockfile(lock, {"MYPY_VERSION": "2.4.0"})
    assert changes and not errors
    assert str(baseline) in run.call_args.args[0]


def test_regenerate_group_only_compile_uses_local_pyproject(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    Path("pyproject.toml").write_text("[dependency-groups]\ndev=['mypy>=2']\n")
    lock = Path("requirements.lock")
    lock.write_text("# uv pip compile --group dev -o requirements.lock\nmypy==2.4.0\n")
    run = Mock()
    monkeypatch.setattr(sdd.subprocess, "run", run)
    _, errors = sdd.regenerate_lockfile(lock, {"MYPY_VERSION": "2.4.0"})
    assert not errors
    run.assert_called_once()
    Path("pyproject.toml").unlink()
    run.reset_mock()
    _, errors = sdd.regenerate_lockfile(lock, {"MYPY_VERSION": "2.4.0"})
    assert errors
    run.assert_not_called()


@pytest.mark.parametrize(
    "repo,expected",
    [
        ("github.com/psf/black", "psf/black"),
        ("GITHUB.COM/psf/black", "psf/black"),
        ("github.com.evil/psf/black", "github.com.evil/psf/black"),
        ("evil/github.com/psf/black", "evil/github.com/psf/black"),
    ],
)
def test_precommit_bare_domain_is_exact_segment(repo, expected):
    assert sdd._pre_commit_repo_name("- repo: " + repo) == expected


def test_regenerate_unchanged_lock_is_noop(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    Path("pyproject.toml").write_text("[project]\nname='example'\nversion='1'\n")
    lock = Path("requirements.lock")
    lock.write_text("# uv pip compile pyproject.toml -o requirements.lock\nmypy==2.4.0\n")
    monkeypatch.setattr(sdd.subprocess, "run", Mock())
    assert sdd.regenerate_lockfile(lock, {"MYPY_VERSION": "2.4.0"}) == ([], [])


@pytest.mark.parametrize("flag", ["--constraints", "--overrides"])
def test_regenerate_plural_uv_constraints(tmp_path, monkeypatch, flag):
    monkeypatch.chdir(tmp_path)
    Path("pyproject.toml").write_text("[project]\nname='example'\nversion='1'\n")
    Path("constraints.txt").write_text("mypy>=2\n")
    lock = Path("requirements.lock")
    lock.write_text(
        f"# uv pip compile pyproject.toml {flag} constraints.txt -o requirements.lock\nmypy==2.4.0\n"
    )
    run = Mock()
    monkeypatch.setattr(sdd.subprocess, "run", run)
    _, errors = sdd.regenerate_lockfile(lock, {"MYPY_VERSION": "2.4.0"})
    assert not errors
    run.assert_called_once()


def test_regenerate_lock_rejects_external_output_symlink(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    Path("pyproject.toml").write_text("[project]\nname='example'\nversion='1'\n")
    external = tmp_path.parent / "external-lock"
    external.write_text("# uv pip compile pyproject.toml -o requirements.lock\nmypy==2.4.0\n")
    lock = Path("requirements.lock")
    lock.symlink_to(external)
    run = Mock()
    monkeypatch.setattr(sdd.subprocess, "run", run)
    changes, errors = sdd.regenerate_lockfile(lock, {"MYPY_VERSION": "2.4.0"})
    assert not changes and errors
    run.assert_not_called()


def test_regenerate_lock_fails_closed_on_solver_failure(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    Path("pyproject.toml").write_text("[project]\nname='example'\nversion='1'\n")
    lock = Path("requirements.lock")
    lock.write_text(
        "# This file was autogenerated by uv via the following command:\n#    uv pip compile pyproject.toml -o requirements.lock\nmypy==2.4.0\n"
    )
    monkeypatch.setattr(
        sdd.subprocess, "run", Mock(side_effect=sdd.subprocess.CalledProcessError(1, ["uv"]))
    )
    changes, errors = sdd.regenerate_lockfile(lock, {"MYPY_VERSION": "2.4.0"})
    assert changes == [] and "failed" in errors[0]


def test_regenerate_manual_requirement_list_stays_direct_pin_only(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    lock = Path("requirements-dev.txt")
    lock.write_text("mypy==2.4.0\n")
    run = Mock()
    monkeypatch.setattr(sdd.subprocess, "run", run)
    assert sdd.regenerate_lockfile(lock, {"MYPY_VERSION": "2.4.0"}) == ([], [])
    run.assert_not_called()


def test_resolve_locks_requires_apply():
    with pytest.raises(SystemExit) as error:
        sdd.main(["--check", "--resolve-locks"])
    assert error.value.code == 2


def _write_env_file(path: Path, versions: dict[str, str]) -> None:
    lines = [f"{key}={value}" for key, value in versions.items()]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_pyproject(path: Path, ruff_version: str, black_version: str) -> None:
    content = "\n".join(
        [
            "[project.optional-dependencies]",
            "dev = [",
            f'  "ruff=={ruff_version}",',
            f'  "black=={black_version}",',
            "]",
            "",
        ]
    )
    path.write_text(content, encoding="utf-8")


def test_sync_lockfile_skips_missing_file(tmp_path: Path) -> None:
    missing = tmp_path / "requirements.lock"
    pins = {"RUFF_VERSION": "1.0.0"}

    changes, errors = sdd.sync_lockfile(missing, pins, apply=False)

    assert changes == []
    assert errors == []


def test_sync_lockfile_apply_updates_versions(tmp_path: Path) -> None:
    lockfile = tmp_path / "requirements.lock"
    lockfile.write_text(
        "\n".join(
            [
                "ruff==0.1.0",
                "black==0.2.0",
                "requests==2.0.0",
                "# comment",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    pins = {"RUFF_VERSION": "1.0.0", "BLACK_VERSION": "2.0.0"}

    changes, errors = sdd.sync_lockfile(lockfile, pins, apply=True)

    assert errors == []
    assert "requirements.lock:ruff: 0.1.0 -> ==1.0.0" in changes
    assert "requirements.lock:black: 0.2.0 -> ==2.0.0" in changes
    updated = lockfile.read_text(encoding="utf-8")
    assert "ruff==1.0.0" in updated
    assert "black==2.0.0" in updated
    assert "requests==2.0.0" in updated


def test_sync_lockfile_reports_requirements_dev_lockfile_name(tmp_path: Path) -> None:
    lockfile = tmp_path / "requirements-dev.lock"
    lockfile.write_text("ruff==0.1.0\n", encoding="utf-8")

    changes, errors = sdd.sync_lockfile(
        lockfile,
        {"RUFF_VERSION": "1.0.0"},
        apply=False,
    )

    assert errors == []
    assert changes == ["requirements-dev.lock:ruff: 0.1.0 -> ==1.0.0"]


def test_sync_lockfile_preserves_comments_and_whitespace(tmp_path: Path) -> None:
    lockfile = tmp_path / "requirements.lock"
    lockfile.write_text(
        "\n".join(
            [
                "  ruff==0.1.0  # pinned",
                "black==0.2.0",
                "  # comment-only",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    pins = {"RUFF_VERSION": "1.0.0", "BLACK_VERSION": "2.0.0"}

    changes, errors = sdd.sync_lockfile(lockfile, pins, apply=True)

    assert errors == []
    assert "requirements.lock:ruff: 0.1.0 -> ==1.0.0" in changes
    assert "requirements.lock:black: 0.2.0 -> ==2.0.0" in changes
    updated = lockfile.read_text(encoding="utf-8")
    assert "  ruff==1.0.0  # pinned" in updated
    assert "black==2.0.0" in updated


def test_sync_lockfile_normalizes_non_exact_and_unversioned_requirements(tmp_path: Path) -> None:
    lockfile = tmp_path / "requirements-dev.txt"
    lockfile.write_text(
        "black>=0.2.0\nruff\nmypy[reports]~=1.2.0 ; python_version >= '3.10'\n",
        encoding="utf-8",
    )

    changes, errors = sdd.sync_lockfile(
        lockfile,
        {"BLACK_VERSION": "2.0.0", "RUFF_VERSION": "1.0.0", "MYPY_VERSION": "1.3.0"},
        apply=True,
    )

    assert errors == []
    assert changes == [
        "requirements-dev.txt:black: >=0.2.0 -> ==2.0.0",
        "requirements-dev.txt:ruff: (unversioned) -> ==1.0.0",
        "requirements-dev.txt:mypy: ~=1.2.0 -> ==1.3.0",
    ]
    assert lockfile.read_text(encoding="utf-8") == (
        "black==2.0.0\nruff==1.0.0\n" "mypy[reports]==1.3.0 ; python_version >= '3.10'\n"
    )


def test_sync_pyproject_normalizes_minimum_pin_at_target_version(
    tmp_path: Path,
) -> None:
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(
        '[project.optional-dependencies]\ndev = [\n  "black>=2.0.0",\n]\n',
        encoding="utf-8",
    )

    changes, errors = sdd.sync_pyproject(
        pyproject,
        {"BLACK_VERSION": "2.0.0"},
        apply=True,
    )

    assert errors == []
    assert changes == ["black: >=2.0.0 -> ==2.0.0"]
    assert '"black==2.0.0"' in pyproject.read_text(encoding="utf-8")


def test_main_preserves_tool_only_pyproject_and_updates_lockfile(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    env_path = tmp_path / "pins.env"
    pyproject_path = tmp_path / "pyproject.toml"
    lockfile = tmp_path / "requirements.lock"
    _write_env_file(env_path, {"RUFF_VERSION": "1.0.0"})
    tool_config = "[tool.ruff]\nline-length = 99\n"
    pyproject_path.write_text(tool_config, encoding="utf-8")
    lockfile.write_text("ruff==0.9.0\n", encoding="utf-8")
    monkeypatch.chdir(tmp_path)

    assert (
        sdd.main(
            [
                "--apply",
                "--create-if-missing",
                "--pin-file",
                str(env_path),
                "--pyproject",
                str(pyproject_path),
            ]
        )
        == 0
    )
    assert pyproject_path.read_text(encoding="utf-8") == tool_config
    assert lockfile.read_text(encoding="utf-8") == "ruff==1.0.0\n"


def test_sync_pyproject_rejects_package_without_project_section(tmp_path: Path) -> None:
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(
        '[build-system]\nrequires = ["setuptools"]\n',
        encoding="utf-8",
    )

    changes, errors = sdd.sync_pyproject(
        pyproject,
        {"RUFF_VERSION": "1.0.0"},
        apply=True,
        create_if_missing=True,
    )

    assert changes == []
    assert errors == ["Could not find [project] section to add optional-dependencies"]
    assert pyproject.read_text(encoding="utf-8") == ('[build-system]\nrequires = ["setuptools"]\n')


@pytest.mark.parametrize("legacy_file", ["setup.py", "setup.cfg"])
def test_sync_pyproject_rejects_legacy_package_without_project_section(
    tmp_path: Path, legacy_file: str
) -> None:
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text("[tool.ruff]\nline-length = 99\n", encoding="utf-8")
    (tmp_path / legacy_file).write_text("# legacy package\n", encoding="utf-8")

    changes, errors = sdd.sync_pyproject(
        pyproject,
        {"RUFF_VERSION": "1.0.0"},
        apply=True,
        create_if_missing=True,
    )

    assert changes == []
    assert errors == ["Could not find [project] section to add optional-dependencies"]
    assert pyproject.read_text(encoding="utf-8") == "[tool.ruff]\nline-length = 99\n"


def test_main_apply_updates_pyproject_and_lockfile(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    env_path = tmp_path / "pins.env"
    pyproject_path = tmp_path / "pyproject.toml"
    lockfile = tmp_path / "requirements.lock"
    pins = {"RUFF_VERSION": "1.0.0", "BLACK_VERSION": "2.0.0"}

    _write_env_file(env_path, pins)
    _write_pyproject(pyproject_path, "0.9.0", "2.0.0")
    lockfile.write_text("ruff==0.9.0\n", encoding="utf-8")

    monkeypatch.chdir(tmp_path)

    exit_code = sdd.main(
        [
            "--apply",
            "--lockfile",
            "--pin-file",
            str(env_path),
            "--pyproject",
            str(pyproject_path),
        ]
    )

    assert exit_code == 0
    assert "ruff==1.0.0" in pyproject_path.read_text(encoding="utf-8")
    assert "ruff==1.0.0" in lockfile.read_text(encoding="utf-8")


def test_main_apply_updates_all_present_requirements_lockfiles(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    env_path = tmp_path / "pins.env"
    pyproject_path = tmp_path / "pyproject.toml"
    requirements_lock = tmp_path / "requirements.lock"
    requirements_dev_lock = tmp_path / "requirements-dev.lock"
    requirements_dev_txt = tmp_path / "requirements-dev.txt"
    pins = {"RUFF_VERSION": "1.0.0", "BLACK_VERSION": "2.0.0"}

    _write_env_file(env_path, pins)
    _write_pyproject(pyproject_path, "0.9.0", "2.0.0")
    requirements_lock.write_text("ruff==0.9.0\n", encoding="utf-8")
    requirements_dev_lock.write_text("ruff==0.8.0\n", encoding="utf-8")
    requirements_dev_txt.write_text("ruff==0.7.0\n", encoding="utf-8")
    monkeypatch.chdir(tmp_path)

    exit_code = sdd.main(
        [
            "--apply",
            "--pin-file",
            str(env_path),
            "--pyproject",
            str(pyproject_path),
        ]
    )

    assert exit_code == 0
    assert requirements_lock.read_text(encoding="utf-8") == "ruff==1.0.0\n"
    assert requirements_dev_lock.read_text(encoding="utf-8") == "ruff==1.0.0\n"
    assert requirements_dev_txt.read_text(encoding="utf-8") == "ruff==1.0.0\n"


def test_main_check_reports_lockfile_mismatch(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """Deliberate-break AC: mismatched managed pin fails with exact path:tool."""
    env_path = tmp_path / "pins.env"
    pyproject_path = tmp_path / "pyproject.toml"
    lockfile = tmp_path / "requirements.lock"
    pins = {"RUFF_VERSION": "1.0.0", "BLACK_VERSION": "2.0.0"}

    _write_env_file(env_path, pins)
    _write_pyproject(pyproject_path, "1.0.0", "2.0.0")
    lockfile.write_text("ruff==0.9.0\n", encoding="utf-8")

    monkeypatch.chdir(tmp_path)

    exit_code = sdd.main(
        [
            "--check",
            "--lockfile",
            "--pin-file",
            str(env_path),
            "--pyproject",
            str(pyproject_path),
        ]
    )
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "requirements.lock:ruff" in captured.out
    assert "0.9.0 -> ==1.0.0" in captured.out


def test_main_check_auto_syncs_lockfile_when_present(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    env_path = tmp_path / "pins.env"
    pyproject_path = tmp_path / "pyproject.toml"
    lockfile = tmp_path / "requirements.lock"
    pins = {"RUFF_VERSION": "1.0.0", "BLACK_VERSION": "2.0.0"}

    _write_env_file(env_path, pins)
    _write_pyproject(pyproject_path, "1.0.0", "2.0.0")
    lockfile.write_text("ruff==0.9.0\n", encoding="utf-8")

    monkeypatch.chdir(tmp_path)

    exit_code = sdd.main(
        [
            "--check",
            "--pin-file",
            str(env_path),
            "--pyproject",
            str(pyproject_path),
        ]
    )
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "requirements.lock:ruff" in captured.out


def test_main_check_skips_missing_lockfile(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    env_path = tmp_path / "pins.env"
    pyproject_path = tmp_path / "pyproject.toml"
    pins = {"RUFF_VERSION": "1.0.0", "BLACK_VERSION": "2.0.0"}

    _write_env_file(env_path, pins)
    _write_pyproject(pyproject_path, "1.0.0", "2.0.0")

    monkeypatch.chdir(tmp_path)

    exit_code = sdd.main(
        [
            "--check",
            "--lockfile",
            "--pin-file",
            str(env_path),
            "--pyproject",
            str(pyproject_path),
        ]
    )

    assert exit_code == 0
